version: '3'


tasks:
  install:
    sources:
      - ./package*.json
      - ./node_modules/**/*
    cmds: 
      - npm i
  
  build:
    sources:
      - ./lib/**/*
      - ./package*.json
      - ./node_modules/**/*
      - ./tsconfig.json
    generates:
      - ./dist/**/*
    deps:
      - install
    cmds:
      - test -d ./dist || rm -rf dist
      - npx tsc