/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    // implementation(libs.guava)

    // implementation("io.opentelemetry:opentelemetry-api:1.33.0");
    // implementation("io.opentelemetry:opentelemetry-sdk:1.33.0");
    // implementation("io.opentelemetry:opentelemetry-sdk-metrics:1.33.0");
    // implementation("io.opentelemetry:opentelemetry-exporter-logging:1.33.0");
    // implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.33.0");
    // implementation("io.opentelemetry:opentelemetry-exporter-otlp-http-trace:1.14.0");
    // implementation("io.opentelemetry.semconv:opentelemetry-semconv:1.21.0-alpha")

    implementation("com.bensivo.otel.tracing:lib")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.bensivo.otel.tracing.demo.basic.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}