version: '3'

includes:
  jaeger:
    taskfile: ./packages/jaeger/Taskfile.yml
    dir: ./packages/jaeger/
  python-tracer-demo-basic:
    taskfile: ./packages/python-tracer-demo-basic/Taskfile.yml
    dir: ./packages/python-tracer-demo-basic/
  python-tracer-demo-sender:
    taskfile: ./packages/python-tracer-demo-sender/Taskfile.yml
    dir: ./packages/python-tracer-demo-sender/
  python-tracer-demo-receiver:
    taskfile: ./packages/python-tracer-demo-receiver/Taskfile.yml
    dir: ./packages/python-tracer-demo-receiver/
  nodejs-tracer:
    taskfile: ./packages/nodejs-tracer/Taskfile.yml
    dir: ./packages/nodejs-tracer/
  nodejs-tracer-demo-basic:
    taskfile: ./packages/nodejs-tracer-demo-basic/Taskfile.yml
    dir: ./packages/nodejs-tracer-demo-basic/
  nodejs-tracer-demo-sender:
    taskfile: ./packages/nodejs-tracer-demo-sender/Taskfile.yml
    dir: ./packages/nodejs-tracer-demo-sender/
  nodejs-tracer-demo-receiver:
    taskfile: ./packages/nodejs-tracer-demo-receiver/Taskfile.yml
    dir: ./packages/nodejs-tracer-demo-receiver/
  java-tracer:
    taskfile: ./packages/java-tracer/Taskfile.yml
    dir: ./packages/java-tracer/
  java-tracer-demo-basic:
    taskfile: ./packages/java-tracer-demo-basic/Taskfile.yml
    dir: ./packages/java-tracer-demo-basic/

tasks:
  nodejs-sender-receiver:
    cmds:
      # Start the 'dev' task for service and webapp, as background processes
      - |
        source ./scripts/functions.sh;
        prefix-green "receiver" task nodejs-tracer-demo-receiver:run &
        sleep 3  # Give the receiver time to start up
        prefix-yellow "sender" task nodejs-tracer-demo-sender:run &
        wait

  python-sender-receiver:
    cmds:
      # Start the 'dev' task for service and webapp, as background processes
      - |
        source ./scripts/functions.sh;
        prefix-green "receiver" task python-tracer-demo-receiver:run &
        sleep 3  # Give the receiver time to start up
        prefix-yellow "sender" task python-tracer-demo-sender:run &
        wait